### ISSUE TITLE
(IMPORT FAILED): comfyui-popup_preview

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [NimaNzrii/comfyui-popup_preview#3]
I can't seem to install this at all, I've retried several times. Both by installing missing nodes, and manually installing from this repo.

When restarting Comfy, I get this in my import custom nodes section:
(IMPORT FAILED): C:\AI\ComfyUI\custom_nodes\comfyui-popup_preview

In the workflow, I get this:
![image](https://github.com/NimaNzrii/comfyui-popup_preview/assets/60541708/dcdc7870-1c39-47d4-821a-2b49b2c4e555)

And in "Install missing nodes", I get this:
![image](https://github.com/NimaNzrii/comfyui-popup_preview/assets/60541708/6989ba7e-d833-42cc-822c-e6cfe30baa85)

I have tried to uninstall and reinstall from there, it's just not starting with Comfy.
The files are downloaded fine.
I have tried running the setup.bat as well.

Any suggestions?

**Comment by uoo2** [comment]
same problem   :(

**Comment by ViratX** [comment]
1+ same problem

**Comment by NimaNzrii** [comment]
could you please send whole error?

**Comment by MNeMoNiCuZ** [comment]
In the console when trying to run the workflow:

```
Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: C:\AI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
Error: OpenAI API key is invalid OpenAI features wont work for you
QualityOfLifeSuit_Omar92::NSP ready
[comfy_mtb] | WARNING -> Found multiple match, we will pick the first C:\AI\ComfyUI\models\upscale_models
['C:\\AI\\ComfyUI\\models\\upscale_models', 'C:\\AI\\stable-diffusion-webui\\models/ESRGAN', 'C:\\AI\\stable-diffusion-webui\\models/RealESRGAN', 'C:\\AI\\stable-diffusion-webui\\models/SwinIR']
[comfy_mtb] | WARNING -> No Face Restore checkpoints found at C:\AI\ComfyUI\models\face_restore (if you've used mtb before these checkpoints were saved in upscale_models before)
[comfy_mtb] | WARNING -> For now we fallback to upscale_models but this will be removed in a future version
Error handling request
Traceback (most recent call last):
  File "C:\Users\MNeMiC\AppData\Roaming\Python\Python311\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MNeMiC\AppData\Roaming\Python\Python311\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MNeMiC\AppData\Roaming\Python\Python311\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI\server.py", line 46, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI\custom_nodes\comfyui-workspace-manager\__init__.py", line 233, in update_file
    file.write(json_str)
  File "C:\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 2531-2532: character maps to <undefined>
```

Importing of node when launching:
  0.0 seconds (IMPORT FAILED): C:\AI\ComfyUI\custom_nodes\comfyui-popup_preview

![image](https://github.com/NimaNzrii/comfyui-popup_preview/assets/60541708/1970efd5-86cf-40c9-b5c7-707ee62e2b50)

**Comment by ViratX** [comment]
Yes, this above screen shot is exactly what I get as the error message. I've tried installing it through Comfy Manager as well as Git Clone.

**Comment by NimaNzrii** [comment]
Are you using portable version of comfyui?

**Comment by MNeMoNiCuZ** [comment]
No, the github cloned version.
All up-to-date yesterday before I posted my last message.

**Comment by uoo2** [comment]
> No, the github cloned version. All up-to-date yesterday before I posted my last message.

me too, same cloned version

**Comment by ViratX** [comment]
I am using the one installed from Stability Matrix.

**Comment by K-O-N-B** [comment]
same problem, please fix it

**Comment by NimaNzrii** [comment]
The issue's resolved, you've updated, and now enjoy! 💖
The problem was in the non-portable versions of Comfy UI, which were sending the wrong return address. This got fixed by changing the library.

**Comment by MNeMoNiCuZ** [comment]
Great! Confirmed to work for me, I took a full Comfy update and it all just worked (loading the node pack, I haven't tried using it yet).

Great job!

**Comment by ronaldluka** [comment]
I still can't get it to work. Here is a copy of the error code.
I have the portable version


Error occurred when executing PreviewPopup:


PreviewPopup.() takes 0 positional arguments but 1 was given

File "I:\ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "I:\ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "I:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_ezXY\autoCastPatch.py", line 265, in map_node_over_list
_info = obj.INPUT_TYPES()
^^^^^^^^^^^^^^^^^
