### ISSUE TITLE
[WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by Troyificus** [NimaNzrii/comfyui-popup_preview#5]
Trying to run PreviewPopup for the first time and the workflow keeps failing as soon as it hits this node. It's a fresh install of the node and ComfyUI is up to date. Error is as follows;

`Error occurred when executing PreviewPopup:

[WinError 2] The system cannot find the file specified

  File "C:\Users\Trism\ComfyUI_windows_portable\ComfyUI\execution.py", line 154, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\Users\Trism\ComfyUI_windows_portable\ComfyUI\execution.py", line 84, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\Users\Trism\ComfyUI_windows_portable\ComfyUI\execution.py", line 77, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\Users\Trism\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-popup_preview\popup.py", line 50, in execute
    save_image(image, subpath)
  File "C:\Users\Trism\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-popup_preview\popup.py", line 30, in save_image
    execute_after_save()
  File "C:\Users\Trism\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-popup_preview\popup.py", line 15, in execute_after_save
    subprocess.Popen([Python_patch, 'popup_window.py'])
  File "subprocess.py", line 971, in __init__
  File "subprocess.py", line 1440, in _execute_child`

**Comment by Aljnk** [comment]
Hi, I have the almost same problem except number of lines:
```
File "C:\Users\sasha\OneDrive\Desktop\Portable\ComfyUI\ComfyUI\custom_nodes\comfyui-popup_preview\popup.py", line 55, in execute
save_image(image, subpath)
File "C:\Users\sasha\OneDrive\Desktop\Portable\ComfyUI\ComfyUI\custom_nodes\comfyui-popup_preview\popup.py", line 35, in save_image
openWindow()
File "C:\Users\sasha\OneDrive\Desktop\Portable\ComfyUI\ComfyUI\custom_nodes\comfyui-popup_preview\popup.py", line 20, in openWindow
subprocess.Popen([Python_patch, popup_window_path])
```

All updated just now.

**Comment by NimaNzrii** [comment]
hi . i have fixed Troyificus problem. but i cant understand what is exactly happening on your case. could you please update the node and send the error log again?
i had changed some codes to get better log to fix your problem as soon as possible💖

**Comment by Aljnk** [comment]
I try to understand this problem.
I think it happen here:
`python_running = any(p.info['exe'] == Python_patch for p in psutil.process_iter(['pid', 'name', 'exe']))`

my log ->
`Python_patch = ...\ComfyUI\ComfyUI\custom_nodes\comfyui-popup_preview\window\venv\Scripts\python.exe`

```
p.info > ...\ComfyUI\python_embeded\python.exe
... many other p.info
```

**Comment by NimaNzrii** [comment]
The problem does not seem to be in this part of the code. Please update the node and send the new log in full. I promise to solve the problem much sooner than you think

**Comment by Aljnk** [comment]
ok :)

**Comment by Aljnk** [comment]
Python not exist on: C:\Users\sasha\OneDrive\Desktop\Portable\ComfyUI\ComfyUI\custom_nodes\comfyui-popup_preview\window\venv\Scripts\python.exe and this is popup window path C:\Users\sasha\OneDrive\Desktop\Portable\ComfyUI\ComfyUI\custom_nodes\comfyui-popup_preview\window\popup_window.py

**Comment by NimaNzrii** [comment]
did you tried to run setup.bat manually?
its on comfyui-popup_preview\window\setup.bat

**Comment by Aljnk** [comment]
setup.bat log
```
Installing PopUp Preview...
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
The system cannot find the specified path.
The system cannot find the specified path.
Installing requirements...
"pip" is not internal or external
command, executable program, or batch file.
installed successfully
```

**Comment by Aljnk** [comment]
:)
I think I don't have python on my local machine.

**Comment by Aljnk** [comment]
Change your file so that if there is no local Python, the installation of Python comes from comfyUI.

```
@echo off

set PYTHON_EMBEDDED_PATH="..\..\..\..\python_embeded\python.exe"

IF EXIST venv (
    echo Deleting existing venv...
    RMDIR /S /Q venv
)

echo Installing PopUp Preview...

python --version >nul 2>nul
IF ERRORLEVEL 1 (
    echo Local Python not found, using embedded Python...
	
    %PYTHON_EMBEDDED_PATH% -m pip show venv >nul 2>nul
    IF ERRORLEVEL 1 (
        %PYTHON_EMBEDDED_PATH% -m pip install virtualenv
    )
    %PYTHON_EMBEDDED_PATH% -m virtualenv venv
) ELSE (
    echo Local Python found, using local Python...
    python -m venv venv
)

call .\venv\Scripts\deactivate.bat

call .\venv\Scripts\activate.bat

echo Installing requirements...

python --version >nul 2>nul
IF ERRORLEVEL 1 (
    echo Local pip not found, using pip from venv...
    .\venv\Scripts\pip.exe install -r requirements.txt
) ELSE (
    echo Local pip found, using local pip...
    pip install -r requirements.txt
)

echo installed successfully
```

now I see "venv" folder

![image](https://github.com/NimaNzrii/comfyui-popup_preview/assets/11256478/bb736e12-abd6-421d-a18a-82e97648eb4d)

**Comment by Aljnk** [comment]
But now :)

Traceback (most recent call last):
  File "...\comfyui-popup_preview\window\popup_window.py", line 2, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'

**Comment by NimaNzrii** [comment]
it seems that the problem is still from your python file. try to install python from Microsoft store and run setup bat again

if you still had same problem. dont worry , im working on a plugin on photoshop so you dont need popup preview at all

**Comment by Aljnk** [comment]
I don't want to install Python locally. I'll try to get the result by installing the necessary things of Python from ComfyUI.

**Comment by NimaNzrii** [comment]
![Big](https://github.com/NimaNzrii/comfyui-popup_preview/assets/148809650/54ad4067-82e5-4aa7-b809-548965f3bc40)

**Comment by Aljnk** [comment]
I decided not to bother and just install local python.

Work :)

Do you use "Auto Queue" for live update?
